// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travellers.Models;

#nullable disable

namespace Travellers.Migrations
{
    [DbContext(typeof(TravellerContext))]
    partial class TravellerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Travellers.Models.Booking", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("booking_id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsConfirmed")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<long>("phone_number")
                        .HasColumnType("bigint");

                    b.Property<string>("residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("traveller_count")
                        .HasColumnType("int");

                    b.Property<int>("traveller_id")
                        .HasColumnType("int");

                    b.Property<string>("vacation_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("booking_id");

                    b.HasIndex("traveller_id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("Travellers.Models.Feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("traveller_id")
                        .HasColumnType("int");

                    b.HasKey("feedback_id");

                    b.HasIndex("traveller_id");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("Travellers.Models.Payments", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payment_id"));

                    b.Property<int?>("Bookingsbooking_id")
                        .HasColumnType("int");

                    b.Property<int>("booking_id")
                        .HasColumnType("int");

                    b.Property<int>("card_number")
                        .HasColumnType("int");

                    b.Property<int>("cvv_number")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int?>("traveller_id")
                        .HasColumnType("int");

                    b.Property<string>("traveller_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("payment_id");

                    b.HasIndex("Bookingsbooking_id");

                    b.HasIndex("traveller_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Travellers.Models.Traveller", b =>
                {
                    b.Property<int>("traveller_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("traveller_id"));

                    b.Property<long>("phone_number")
                        .HasColumnType("bigint");

                    b.Property<string>("traveller_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("traveller_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("traveller_password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("traveller_id");

                    b.ToTable("traveller");
                });

            modelBuilder.Entity("Travellers.Models.Booking", b =>
                {
                    b.HasOne("Travellers.Models.Traveller", "traveller")
                        .WithMany("Bookings")
                        .HasForeignKey("traveller_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("traveller");
                });

            modelBuilder.Entity("Travellers.Models.Feedback", b =>
                {
                    b.HasOne("Travellers.Models.Traveller", "traveller")
                        .WithMany()
                        .HasForeignKey("traveller_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("traveller");
                });

            modelBuilder.Entity("Travellers.Models.Payments", b =>
                {
                    b.HasOne("Travellers.Models.Booking", "Bookings")
                        .WithMany()
                        .HasForeignKey("Bookingsbooking_id");

                    b.HasOne("Travellers.Models.Traveller", "traveller")
                        .WithMany()
                        .HasForeignKey("traveller_id");

                    b.Navigation("Bookings");

                    b.Navigation("traveller");
                });

            modelBuilder.Entity("Travellers.Models.Traveller", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
